# Generated by Django 6.0.7 on 2026-09-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('module', 'Module'), ('class', 'Class'), ('function', 'Function')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=1024)),
                ('signature', models.TextField()),
                ('source_hash', models.CharField(max_length=64)),
                ('file_path', models.CharField(max_length=512)),
                ('line_number', models.IntegerField()),
                ('existing_docstring', models.TextField(blank=True, null=True)),
                ('generated_docstring', models.TextField(blank=True, null=True)),
                ('doc_source', models.CharField(choices=[('generated', 'LLM Generated'), ('copied', 'Copied from Previous Snapshot'), ('existing', 'Existing in Source Code'), ('none', 'No Documentation')], default='none', max_length=10)),
                ('doc_last_generated', models.DateTimeField(blank=True, null=True)),
                ('source_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analysis.codeentity')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing Code'), ('parsing_complete', 'Parsing Complete'), ('generating_docs', 'Generating Documentation'), ('docs_complete', 'Documentation Complete'), ('detecting_drift', 'Detecting Drift'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_entities', models.IntegerField(default=0)),
                ('entities_documented', models.IntegerField(default=0)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('temp_path', models.CharField(blank=True, max_length=512, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repositories.repository')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DriftFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('stale_doc', 'Stale Documentation'), ('new_undocumented', 'New Undocumented Code'), ('orphaned_doc', 'Orphaned Documentation'), ('signature_changed', 'Signature Changed')], max_length=20)),
                ('qualified_name', models.CharField(max_length=1024)),
                ('detail', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_flags_current', to='analysis.codeentity')),
                ('previous_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_flags_previous', to='analysis.codeentity')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_flags', to='repositories.repository')),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_flags_as_current', to='analysis.snapshot')),
                ('previous_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_flags_as_previous', to='analysis.snapshot')),
            ],
            options={
                'ordering': ['flag_type', 'qualified_name'],
            },
        ),
        migrations.AddField(
            model_name='codeentity',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='analysis.snapshot'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['repository', '-timestamp'], name='analysis_sn_reposit_839f65_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['status'], name='analysis_sn_status_47d113_idx'),
        ),
        migrations.AddIndex(
            model_name='driftflag',
            index=models.Index(fields=['repository', 'current_snapshot'], name='analysis_dr_reposit_b8fe02_idx'),
        ),
        migrations.AddIndex(
            model_name='driftflag',
            index=models.Index(fields=['flag_type'], name='analysis_dr_flag_ty_065e50_idx'),
        ),
        migrations.AddIndex(
            model_name='codeentity',
            index=models.Index(fields=['snapshot', 'entity_type'], name='analysis_co_snapsho_7b4eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='codeentity',
            index=models.Index(fields=['snapshot', 'qualified_name'], name='analysis_co_snapsho_aae830_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codeentity',
            unique_together={('snapshot', 'qualified_name')},
        ),
    ]
