# Generated by Django 5.1.1 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_parse', 'Ready to Parse'), ('parsing', 'Parsing Code'), ('parsing_complete', 'Parsing Complete'), ('generating_docs', 'Generating Documentation'), ('docs_complete', 'Documentation Complete'), ('detecting_drift', 'Detecting Drift'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
