# Generated by Django 5.1.1 on 2026-09-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
    ]
