# Generated by Django 5.1.1 on 2026-09-01 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_alter_repository_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner', 'name')},
        ),
    ]
